# Generated by Django 3.2.9 on 2021-12-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_orderitem_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='shippingdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('secondname', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('Country', models.CharField(max_length=50)),
                ('StreetAddress', models.CharField(max_length=50)),
                ('StreetAddress2', models.CharField(blank=True, max_length=50, null=True)),
                ('Town_City', models.CharField(max_length=50)),
                ('Postcode_ZIP', models.IntegerField()),
                ('Phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
