# Generated by Django 3.2.9 on 2021-12-12 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_appointment_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='time',
        ),
    ]
