# Generated by Django 4.0 on 2022-01-02 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_customer_header_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='header_image',
            new_name='profile_image',
        ),
    ]
