# Generated by Django 4.0 on 2022-01-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_comments_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
